module.exports = {
  items: [
    {
      categoria: "Embalagens",
      descricao: "Tampa e base",
      quantidade: 2,
      precoUnitario: 24.39,
    },
    {
      categoria: "Embalagens",
      descricao: "Tampa e base",
      quantidade: 2,
      precoUnitario: 23.93,
    },
    {
      categoria: "Alimentos",
      descricao: "Feijao Preto 1 kg",
      quantidade: 8,
      precoUnitario: 9.15,
    },
    {
      categoria: "Alimentos",
      descricao: "Parboílizado 5 kg",
      quantidade: 2,
      precoUnitario: 28.45,
    },
    {
      categoria: "Alimentos",
      descricao: "Farinha de Mandioca",
      quantidade: 7,
      precoUnitario: 4.39,
    },
    {
      categoria: "Alimentos",
      descricao: "Óleo",
      quantidade: 2,
      precoUnitario: 5.49,
    },
    {
      categoria: "Alimentos",
      descricao: "Margarina",
      quantidade: 1,
      precoUnitario: 10.68,
    },
    {
      categoria: "Verduras",
      descricao: "Cebola 1 kg",
      quantidade: 8,
      precoUnitario: 9.99,
    },
    {
      categoria: "Verduras",
      descricao: "Tomate 1 kg",
      quantidade: 6,
      precoUnitario: 8.95,
    },
    {
      categoria: "Verduras",
      descricao: "Pimentão 1 kg",
      quantidade: 4,
      precoUnitario: 12.99,
    },
    {
      categoria: "Verduras",
      descricao: "Chaque Ponta di Agulha",
      quantidade: 7,
      precoUnitario: 27.9,
    },
    {
      categoria: "Verduras",
      descricao: "Colabresa 20 unidades",
      quantidade: 1,
      precoUnitario: 69.49,
    },
    {
      categoria: "Verduras",
      descricao: "Costela Corda Salgada",
      quantidade: 15,
      precoUnitario: 15,
    },
    {
      categoria: "Verduras",
      descricao: "Xaxado",
      quantidade: 5,
      precoUnitario: 10,
    },
    {
      categoria: "Outros",
      descricao: "Couve",
      quantidade: 0,
      precoUnitario: 0,
    },
    { categoria: "Outros", descricao: "Alho", quantidade: 0, precoUnitario: 0 },
  ],
};
